version: '3.5'

services:
  symfony.cqrs.database:
    container_name: "symfony_cqrs_database"
    image: postgres:${POSTGRES_VERSION:-15}-alpine
    environment:
      POSTGRES_DB: ${POSTGRES_DB:-app}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-!ChangeMe!}
      POSTGRES_USER: ${POSTGRES_USER:-app}
    volumes:
      - symfony.cqrs.database:/var/lib/postgresql/data:rw
    networks:
      - symfony.cqrs.network
    ports:
      - "5433:5432"

volumes:
  symfony.cqrs.database:
    name: symfony.cqrs.database
    external: false

networks:
  symfony.cqrs.network:
    name: symfony-cqrs
    driver: bridge